# Generated by Django 5.2.9 on 2025-12-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegexRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('regex_pattern', models.TextField()),
                ('regex_group', models.CharField(blank=True, default='1', max_length=255, null=True)),
            ],
        ),
    ]
