# Generated by Django 5.2.9 on 2025-12-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregexrule',
            name='regex_group',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
