# Generated by Django 5.2.9 on 2025-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex_engine', '0002_alter_customerregexrule_regex_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregexrule',
            name='is_item_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerregexrule',
            name='customer_name',
            field=models.CharField(choices=[('Food Hall', 'Food Hall')], max_length=255),
        ),
    ]
