# Generated by Django 5.2.9 on 2025-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex_engine', '0003_customerregexrule_is_item_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregexrule',
            name='regex_pattern_v2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerregexrule',
            name='regex_pattern_v3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
