# Generated by Django 5.2.9 on 2026-01-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex_engine', '0004_customerregexrule_regex_pattern_v2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregexrule',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date')], default='string', max_length=50),
        ),
    ]
