# Generated by Django 5.2.9 on 2026-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex_engine', '0005_customerregexrule_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPHRegexRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pph_type', models.CharField(choices=[('pph_masukan', 'PPH Masukan'), ('pph_keluaran', 'PPH Keluaran')], default='pph_masukan', max_length=50)),
                ('field_name', models.CharField(max_length=255)),
                ('regex_pattern', models.TextField()),
                ('regex_pattern_v2', models.TextField(blank=True, null=True)),
                ('regex_pattern_v3', models.TextField(blank=True, null=True)),
                ('regex_group', models.IntegerField(blank=True, default=1, null=True)),
                ('is_item_field', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date')], default='string', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PPH Regex Rule',
                'verbose_name_plural': 'PPH Regex Rules',
            },
        ),
    ]
