# Generated by Django 5.2.9 on 2026-01-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex_engine', '0006_add_pph_regex_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pphregexrule',
            name='pph_type',
        ),
        migrations.AddField(
            model_name='pphregexrule',
            name='pph_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pphregexrule',
            name='pph_name',
            field=models.CharField(choices=[('pph_masukan', 'PPH Masukan'), ('pph_keluaran', 'PPH Keluaran')], default='pph_masukan', max_length=255),
            preserve_default=False,
        ),
    ]
