# Generated by Django 5.2.9 on 2026-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(choices=[('Food Hall', 'Food Hall')], max_length=255)),
                ('origin_field', models.CharField(max_length=255)),
                ('destination_field', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Customer Field Mapping',
                'verbose_name_plural': 'Customer Field Mappings',
            },
        ),
    ]
