# Generated by Django 5.2.9 on 2026-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfieldmapping',
            name='is_field_item',
            field=models.BooleanField(default=False),
        ),
    ]
