# Generated by Django 5.2.9 on 2026-01-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mapping', '0002_customerfieldmapping_is_field_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfieldmapping',
            name='destination_field',
        ),
        migrations.RemoveField(
            model_name='customerfieldmapping',
            name='origin_field',
        ),
        migrations.AddField(
            model_name='customerfieldmapping',
            name='destination_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerfieldmapping',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerfieldmapping',
            name='origin_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerfieldmapping',
            name='is_field_item',
            field=models.BooleanField(default=False, verbose_name='Is Field Item'),
        ),
    ]
