# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class RpaCustomerPoHeader(models.Model):
    id = models.BigAutoField(primary_key=True)
    customer_id = models.CharField(max_length=50, blank=True, null=True)
    customer_name = models.CharField(max_length=255, blank=True, null=True)
    customer_pic_po = models.CharField(max_length=255, blank=True, null=True)
    group_customer_id = models.CharField(max_length=50, blank=True, null=True)
    group_customer_name = models.CharField(max_length=255, blank=True, null=True)
    top_id = models.CharField(max_length=100, blank=True, null=True)
    ship_to_customer_name = models.CharField(max_length=255, blank=True, null=True)
    ship_to_address = models.TextField(blank=True, null=True)
    ship_to_city = models.CharField(max_length=100, blank=True, null=True)
    ship_to_postal_code = models.CharField(max_length=20, blank=True, null=True)
    ship_to_phone_1 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_phone_2 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_pic = models.CharField(max_length=255, blank=True, null=True)
    ship_to_customer_address_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_npwp = models.CharField(max_length=100, blank=True, null=True)
    ship_to_top_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_parent_customer_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_sales_origin_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_distribution_channel_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_division_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_customer_address_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_customer_name = models.CharField(max_length=255, blank=True, null=True)
    bill_to_pic = models.CharField(max_length=255, blank=True, null=True)
    bill_to_address = models.TextField(blank=True, null=True)
    bill_to_city = models.CharField(max_length=100, blank=True, null=True)
    bill_to_postal_code = models.CharField(max_length=20, blank=True, null=True)
    bill_to_phone_1 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_phone_2 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_npwp = models.CharField(max_length=100, blank=True, null=True)
    bill_to_top_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_parent_customer_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_type = models.CharField(max_length=10, blank=True, null=True)
    bill_to_sales_org_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_distribution_channel_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_division_id = models.CharField(max_length=50, blank=True, null=True)
    npwp = models.CharField(max_length=100, blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    entry_by = models.CharField(max_length=255, blank=True, null=True)
    customer_po_no = models.CharField(max_length=100, blank=True, null=True)
    tanggal_cetak = models.DateTimeField()
    tanggal_pesan = models.DateTimeField()
    tanggal_kirim = models.DateTimeField()
    expiry_date_po = models.DateTimeField()
    jadwal_jam_pengiriman = models.CharField(max_length=50, blank=True, null=True)
    catatan_pengiriman = models.TextField(blank=True, null=True)
    top = models.CharField(max_length=20, blank=True, null=True)
    tanggal_order_entry = models.DateTimeField()
    jam_order_entry = models.CharField(max_length=20, blank=True, null=True)
    vendor_code = models.CharField(max_length=50, blank=True, null=True)
    discount_po_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    dc_allowance_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    damage_allowance = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pay_allowance_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    total_discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    total_before_discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    total_after_discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    ppn_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ppn_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    has_amount = models.IntegerField(blank=True, null=True)
    total_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    scanned_po = models.TextField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    minimum_expiry_date = models.DateTimeField()
    sales_code = models.CharField(max_length=100, blank=True, null=True)
    customer_po_type = models.IntegerField(blank=True, null=True)
    is_reserve = models.IntegerField(blank=True, null=True)
    date_release_so = models.DateTimeField()
    supplier_id = models.CharField(max_length=100, blank=True, null=True)
    is_full_free = models.IntegerField(blank=True, null=True)
    is_cod = models.IntegerField(blank=True, null=True)
    sales_id = models.IntegerField(blank=True, null=True)
    sales_name = models.CharField(max_length=255, blank=True, null=True)
    ship_to_type = models.CharField(max_length=10, blank=True, null=True)
    ship_to_sales_office = models.CharField(max_length=50, blank=True, null=True)
    ship_to_sales_group = models.CharField(max_length=50, blank=True, null=True)
    ship_to_customer_group1 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_customer_group2 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_customer_group3 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_customer_group4 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_account_group_id = models.CharField(max_length=20, blank=True, null=True)
    ship_to_default_partner1 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_default_partner2 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_warehouse_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_sales_origin_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_sales_office = models.CharField(max_length=50, blank=True, null=True)
    bill_to_sales_group = models.CharField(max_length=50, blank=True, null=True)
    bill_to_customer_group1 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_customer_group2 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_customer_group3 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_customer_group4 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_account_group_id = models.CharField(max_length=20, blank=True, null=True)
    bill_to_default_partner1 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_default_partner2 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_warehouse_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rpa_customer_po_header'


class RpaCustomerPoHeaderDev(models.Model):
    id = models.BigAutoField(primary_key=True)
    customer_id = models.CharField(max_length=50, blank=True, null=True)
    customer_name = models.CharField(max_length=255, blank=True, null=True)
    customer_pic_po = models.CharField(max_length=255, blank=True, null=True)
    group_customer_id = models.CharField(max_length=50, blank=True, null=True)
    group_customer_name = models.CharField(max_length=255, blank=True, null=True)
    top_id = models.CharField(max_length=100, blank=True, null=True)
    ship_to_customer_name = models.CharField(max_length=255, blank=True, null=True)
    ship_to_address = models.TextField(blank=True, null=True)
    ship_to_city = models.CharField(max_length=100, blank=True, null=True)
    ship_to_postal_code = models.CharField(max_length=20, blank=True, null=True)
    ship_to_phone_1 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_phone_2 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_pic = models.CharField(max_length=255, blank=True, null=True)
    ship_to_customer_address_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_npwp = models.CharField(max_length=100, blank=True, null=True)
    ship_to_top_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_parent_customer_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_sales_origin_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_distribution_channel_id = models.CharField(max_length=50, blank=True, null=True)
    ship_to_division_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_customer_address_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_customer_name = models.CharField(max_length=255, blank=True, null=True)
    bill_to_pic = models.CharField(max_length=255, blank=True, null=True)
    bill_to_address = models.TextField(blank=True, null=True)
    bill_to_city = models.CharField(max_length=100, blank=True, null=True)
    bill_to_postal_code = models.CharField(max_length=20, blank=True, null=True)
    bill_to_phone_1 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_phone_2 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_npwp = models.CharField(max_length=100, blank=True, null=True)
    bill_to_top_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_parent_customer_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_type = models.CharField(max_length=10, blank=True, null=True)
    bill_to_sales_org_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_distribution_channel_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_division_id = models.CharField(max_length=50, blank=True, null=True)
    npwp = models.CharField(max_length=100, blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    entry_by = models.CharField(max_length=255, blank=True, null=True)
    customer_po_no = models.CharField(max_length=100, blank=True, null=True)
    tanggal_cetak = models.DateTimeField()
    tanggal_pesan = models.DateTimeField()
    tanggal_kirim = models.DateTimeField()
    expiry_date_po = models.DateTimeField()
    jadwal_jam_pengiriman = models.CharField(max_length=50, blank=True, null=True)
    catatan_pengiriman = models.TextField(blank=True, null=True)
    top = models.CharField(max_length=20, blank=True, null=True)
    tanggal_order_entry = models.DateTimeField()
    jam_order_entry = models.CharField(max_length=20, blank=True, null=True)
    vendor_code = models.CharField(max_length=50, blank=True, null=True)
    discount_po_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    dc_allowance_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    damage_allowance = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pay_allowance_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    total_discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    total_before_discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    total_after_discount_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    ppn_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ppn_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    has_amount = models.IntegerField(blank=True, null=True)
    total_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    scanned_po = models.TextField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    minimum_expiry_date = models.DateTimeField()
    sales_code = models.CharField(max_length=100, blank=True, null=True)
    customer_po_type = models.IntegerField(blank=True, null=True)
    is_reserve = models.IntegerField(blank=True, null=True)
    date_release_so = models.DateTimeField()
    supplier_id = models.CharField(max_length=100, blank=True, null=True)
    is_full_free = models.IntegerField(blank=True, null=True)
    is_cod = models.IntegerField(blank=True, null=True)
    sales_id = models.IntegerField(blank=True, null=True)
    sales_name = models.CharField(max_length=255, blank=True, null=True)
    ship_to_type = models.CharField(max_length=10, blank=True, null=True)
    ship_to_sales_office = models.CharField(max_length=50, blank=True, null=True)
    ship_to_sales_group = models.CharField(max_length=50, blank=True, null=True)
    ship_to_customer_group1 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_customer_group2 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_customer_group3 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_customer_group4 = models.CharField(max_length=10, blank=True, null=True)
    ship_to_account_group_id = models.CharField(max_length=20, blank=True, null=True)
    ship_to_default_partner1 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_default_partner2 = models.CharField(max_length=50, blank=True, null=True)
    ship_to_warehouse_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_sales_origin_id = models.CharField(max_length=50, blank=True, null=True)
    bill_to_sales_office = models.CharField(max_length=50, blank=True, null=True)
    bill_to_sales_group = models.CharField(max_length=50, blank=True, null=True)
    bill_to_customer_group1 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_customer_group2 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_customer_group3 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_customer_group4 = models.CharField(max_length=10, blank=True, null=True)
    bill_to_account_group_id = models.CharField(max_length=20, blank=True, null=True)
    bill_to_default_partner1 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_default_partner2 = models.CharField(max_length=50, blank=True, null=True)
    bill_to_warehouse_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rpa_customer_po_header_dev'


class RpaCustomerPoItems(models.Model):
    id = models.BigAutoField(primary_key=True)
    header_id = models.PositiveBigIntegerField()
    sku_cust_id = models.CharField(max_length=50, blank=True, null=True)
    sku_samb = models.CharField(max_length=50, blank=True, null=True)
    sku_samb_description = models.CharField(max_length=255, blank=True, null=True)
    qty_dipesan = models.IntegerField(blank=True, null=True)
    qty_in_pcs = models.IntegerField(blank=True, null=True)
    uom = models.CharField(max_length=20, blank=True, null=True)
    uom_id = models.CharField(max_length=20, blank=True, null=True)
    free_goods = models.IntegerField(blank=True, null=True)
    expiry_date = models.DateTimeField(blank=True, null=True)
    keterangan = models.TextField(blank=True, null=True)
    free_buy = models.IntegerField(blank=True, null=True)
    free_get = models.IntegerField(blank=True, null=True)
    principle_id = models.CharField(max_length=50, blank=True, null=True)
    disc_1 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    disc_2 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    disc_3 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    disc_4 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    rbp_price_carton = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    rbp_price = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    conversion_factor = models.IntegerField(blank=True, null=True)
    amount_customer = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sku_samb_id = models.CharField(max_length=50, blank=True, null=True)
    master_item_id = models.CharField(max_length=50, blank=True, null=True)
    tax_code = models.CharField(max_length=10, blank=True, null=True)
    tax_description = models.CharField(max_length=255, blank=True, null=True)
    tax_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    item_group_1 = models.CharField(max_length=10, blank=True, null=True)
    item_group_1_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_2 = models.CharField(max_length=10, blank=True, null=True)
    item_group_2_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_3 = models.CharField(max_length=10, blank=True, null=True)
    item_group_3_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_4 = models.CharField(max_length=10, blank=True, null=True)
    item_group_4_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_5 = models.CharField(max_length=10, blank=True, null=True)
    item_group_5_desc = models.CharField(max_length=255, blank=True, null=True)
    condition_record_number = models.CharField(max_length=50, blank=True, null=True)
    qty_pcs_case = models.IntegerField(blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rpa_customer_po_items'


class RpaCustomerPoItemsDev(models.Model):
    id = models.BigAutoField(primary_key=True)
    header_id = models.PositiveBigIntegerField()
    sku_cust_id = models.CharField(max_length=50, blank=True, null=True)
    sku_samb = models.CharField(max_length=50, blank=True, null=True)
    sku_samb_description = models.CharField(max_length=255, blank=True, null=True)
    qty_dipesan = models.IntegerField(blank=True, null=True)
    qty_in_pcs = models.IntegerField(blank=True, null=True)
    uom = models.CharField(max_length=20, blank=True, null=True)
    uom_id = models.CharField(max_length=20, blank=True, null=True)
    free_goods = models.IntegerField(blank=True, null=True)
    expiry_date = models.DateTimeField(blank=True, null=True)
    keterangan = models.TextField(blank=True, null=True)
    free_buy = models.IntegerField(blank=True, null=True)
    free_get = models.IntegerField(blank=True, null=True)
    principle_id = models.CharField(max_length=50, blank=True, null=True)
    disc_1 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    disc_2 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    disc_3 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    disc_4 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    rbp_price_carton = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    rbp_price = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    conversion_factor = models.IntegerField(blank=True, null=True)
    amount_customer = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    sku_samb_id = models.CharField(max_length=50, blank=True, null=True)
    master_item_id = models.CharField(max_length=50, blank=True, null=True)
    tax_code = models.CharField(max_length=10, blank=True, null=True)
    tax_description = models.CharField(max_length=255, blank=True, null=True)
    tax_amount = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    item_group_1 = models.CharField(max_length=10, blank=True, null=True)
    item_group_1_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_2 = models.CharField(max_length=10, blank=True, null=True)
    item_group_2_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_3 = models.CharField(max_length=10, blank=True, null=True)
    item_group_3_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_4 = models.CharField(max_length=10, blank=True, null=True)
    item_group_4_desc = models.CharField(max_length=255, blank=True, null=True)
    item_group_5 = models.CharField(max_length=10, blank=True, null=True)
    item_group_5_desc = models.CharField(max_length=255, blank=True, null=True)
    condition_record_number = models.CharField(max_length=50, blank=True, null=True)
    qty_pcs_case = models.IntegerField(blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rpa_customer_po_items_dev'
