# Generated by Django 5.2.9 on 2025-12-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('extraction_method', models.CharField(choices=[('regex', 'Regex Based Extraction'), ('ai', 'AI Based Extraction')], default='regex', max_length=100)),
                ('model_used', models.CharField(blank=True, max_length=150)),
                ('input_token', models.IntegerField(default=0)),
                ('output_token', models.IntegerField(default=0)),
                ('total_token', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Extraction',
                'verbose_name_plural': 'Extractions',
            },
        ),
        migrations.CreateModel(
            name='PDFExtractionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file_name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('pdf_extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_items', to='pdf_extraction.pdfextraction')),
            ],
        ),
    ]
