# Generated by Django 5.2.9 on 2025-12-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfextractionitem',
            options={'verbose_name': 'PDF Extraction Item', 'verbose_name_plural': 'PDF Extraction Items'},
        ),
        migrations.AddField(
            model_name='pdfextractionitem',
            name='result_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
