# Generated by Django 5.2.9 on 2025-12-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction', '0002_alter_pdfextractionitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfextraction',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pdfextraction',
            name='customer_name',
            field=models.CharField(choices=[('Food Hall', 'Food Hall')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfextraction',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pdfextractionitem',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pdfextractionitem',
            name='pdf_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfextractionitem',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
