# Generated by Django 5.2.9 on 2025-12-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction', '0003_alter_pdfextraction_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfextraction',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pdfextraction',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pdfextractionitem',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pdfextractionitem',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
