# Generated by Django 5.2.9 on 2025-12-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction', '0004_alter_pdfextraction_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfextraction',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
