# Generated by Django 5.2.9 on 2026-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction', '0005_alter_pdfextraction_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfextractionitem',
            name='final_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
