# Generated by Django 5.2.9 on 2026-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction', '0006_pdfextractionitem_final_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfextraction',
            name='extraction_type',
            field=models.CharField(choices=[('customer', 'Customer Extraction'), ('pph_masukan', 'PPH Masukan'), ('pph_keluaran', 'PPH Keluaran')], default='customer', max_length=50),
        ),
    ]
